# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 727)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setStyleSheet("background-color: rgb(31, 62, 90);\n"
"background-color: rgb(21, 43, 62);\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_top.setStyleSheet("")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_top_left = QtWidgets.QFrame(self.frame_top)
        self.frame_top_left.setMaximumSize(QtCore.QSize(30, 25))
        self.frame_top_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_left.setObjectName("frame_top_left")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top_left)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_top_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setMaximumSize(QtCore.QSize(30, 25))
        self.btn_toggle.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-image: url(:/24x24/icons/24x24/cil-menu.png);\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"")
        self.btn_toggle.setText("")
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_3.addWidget(self.btn_toggle)
        self.horizontalLayout_4.addWidget(self.frame_top_left)
        self.frame_middle = QtWidgets.QFrame(self.frame_top)
        self.frame_middle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_middle.setObjectName("frame_middle")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_middle)
        self.horizontalLayout_8.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_des = QtWidgets.QFrame(self.frame_middle)
        self.frame_des.setMaximumSize(QtCore.QSize(200, 25))
        self.frame_des.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_des.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_des.setObjectName("frame_des")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_des)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_des)
        self.frame_icon_top_bar.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 25))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_7.addWidget(self.frame_icon_top_bar)
        self.label_des = QtWidgets.QLabel(self.frame_des)
        self.label_des.setMaximumSize(QtCore.QSize(170, 25))
        self.label_des.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_des.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_des.setObjectName("label_des")
        self.horizontalLayout_7.addWidget(self.label_des)
        self.horizontalLayout_8.addWidget(self.frame_des)
        self.frame_2 = QtWidgets.QFrame(self.frame_middle)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.horizontalLayout_4.addWidget(self.frame_middle)
        self.frame_right = QtWidgets.QFrame(self.frame_top)
        self.frame_right.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(110, 25))
        self.frame_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_right)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_maximize_restore.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_2.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_right)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frame_left_menu.setStyleSheet("")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.home_btn = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn.sizePolicy().hasHeightForWidth())
        self.home_btn.setSizePolicy(sizePolicy)
        self.home_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.home_btn.setMaximumSize(QtCore.QSize(30, 25))
        self.home_btn.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-home.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"")
        self.home_btn.setText("")
        self.home_btn.setFlat(False)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_4.addWidget(self.home_btn)
        self.frame = QtWidgets.QFrame(self.frame_left_menu)
        self.frame.setMaximumSize(QtCore.QSize(30, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4.addWidget(self.frame)
        self.sorting_btn = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sorting_btn.sizePolicy().hasHeightForWidth())
        self.sorting_btn.setSizePolicy(sizePolicy)
        self.sorting_btn.setMaximumSize(QtCore.QSize(50, 100))
        self.sorting_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(75, 100, 122);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"text-align: center\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"\n"
"")
        self.sorting_btn.setCheckable(True)
        self.sorting_btn.setChecked(False)
        self.sorting_btn.setAutoRepeat(False)
        self.sorting_btn.setAutoExclusive(False)
        self.sorting_btn.setObjectName("sorting_btn")
        self.verticalLayout_4.addWidget(self.sorting_btn)
        self.tree_btn = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_btn.sizePolicy().hasHeightForWidth())
        self.tree_btn.setSizePolicy(sizePolicy)
        self.tree_btn.setMaximumSize(QtCore.QSize(50, 100))
        self.tree_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(53, 81, 106);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"text-align: center\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"")
        self.tree_btn.setObjectName("tree_btn")
        self.verticalLayout_4.addWidget(self.tree_btn)
        self.linkedlist_btn = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkedlist_btn.sizePolicy().hasHeightForWidth())
        self.linkedlist_btn.setSizePolicy(sizePolicy)
        self.linkedlist_btn.setMaximumSize(QtCore.QSize(50, 100))
        self.linkedlist_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(27, 55, 81);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"text-align: center\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"\n"
"")
        self.linkedlist_btn.setObjectName("linkedlist_btn")
        self.verticalLayout_4.addWidget(self.linkedlist_btn)
        self.horizontalLayout.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.frame_center)
        self.frame_pages.setStyleSheet("background-color: rgb(24, 49, 72);\n"
"")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(100)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_app_name = QtWidgets.QLabel(self.page_home)
        self.label_app_name.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(80)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_app_name.setFont(font)
        self.label_app_name.setStyleSheet("color: rgb(183, 207, 220) ;\n"
"font: 80pt \"Cantarell\";")
        self.label_app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_app_name.setObjectName("label_app_name")
        self.verticalLayout_5.addWidget(self.label_app_name)
        self.label_app_description = QtWidgets.QLabel(self.page_home)
        self.label_app_description.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_app_description.setFont(font)
        self.label_app_description.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \"Cantarell\";")
        self.label_app_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_app_description.setObjectName("label_app_description")
        self.verticalLayout_5.addWidget(self.label_app_description)
        self.stackedWidget.addWidget(self.page_home)
        self.page_sorting = QtWidgets.QWidget()
        self.page_sorting.setStyleSheet("background-color: rgb(75, 100, 122)")
        self.page_sorting.setObjectName("page_sorting")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_sorting)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_controllers = QtWidgets.QFrame(self.page_sorting)
        self.frame_controllers.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_controllers.setMouseTracking(False)
        self.frame_controllers.setStyleSheet("background-color: rgb(31, 62, 90);\n"
"")
        self.frame_controllers.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_controllers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_controllers.setObjectName("frame_controllers")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_controllers)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_algo = QtWidgets.QFrame(self.frame_controllers)
        self.frame_algo.setMaximumSize(QtCore.QSize(250, 25))
        self.frame_algo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_algo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_algo.setObjectName("frame_algo")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_algo)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_algorithms = QtWidgets.QLabel(self.frame_algo)
        self.label_algorithms.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_algorithms.setAlignment(QtCore.Qt.AlignCenter)
        self.label_algorithms.setObjectName("label_algorithms")
        self.horizontalLayout_11.addWidget(self.label_algorithms)
        self.algorithms = QtWidgets.QComboBox(self.frame_algo)
        self.algorithms.setMaximumSize(QtCore.QSize(150, 16777215))
        self.algorithms.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.algorithms.setObjectName("algorithms")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.algorithms.addItem("")
        self.horizontalLayout_11.addWidget(self.algorithms)
        self.horizontalLayout_12.addWidget(self.frame_algo)
        self.play_control = QtWidgets.QFrame(self.frame_controllers)
        self.play_control.setMaximumSize(QtCore.QSize(350, 25))
        self.play_control.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.play_control.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.play_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.play_control.setObjectName("play_control")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.play_control)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.play_sorting = QtWidgets.QPushButton(self.play_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_sorting.sizePolicy().hasHeightForWidth())
        self.play_sorting.setSizePolicy(sizePolicy)
        self.play_sorting.setMaximumSize(QtCore.QSize(50, 20))
        self.play_sorting.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.play_sorting.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_sorting.setIcon(icon3)
        self.play_sorting.setIconSize(QtCore.QSize(20, 20))
        self.play_sorting.setObjectName("play_sorting")
        self.horizontalLayout_10.addWidget(self.play_sorting)
        self.pause_sorting = QtWidgets.QPushButton(self.play_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_sorting.sizePolicy().hasHeightForWidth())
        self.pause_sorting.setSizePolicy(sizePolicy)
        self.pause_sorting.setMaximumSize(QtCore.QSize(50, 20))
        self.pause_sorting.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(15, 57, 112); \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pause_sorting.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-media-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_sorting.setIcon(icon4)
        self.pause_sorting.setIconSize(QtCore.QSize(20, 20))
        self.pause_sorting.setObjectName("pause_sorting")
        self.horizontalLayout_10.addWidget(self.pause_sorting)
        self.stop_sorting = QtWidgets.QPushButton(self.play_control)
        self.stop_sorting.setMaximumSize(QtCore.QSize(50, 20))
        self.stop_sorting.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(15, 57, 112); \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.stop_sorting.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/24x24/icons/24x24/cil-media-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_sorting.setIcon(icon5)
        self.stop_sorting.setIconSize(QtCore.QSize(20, 20))
        self.stop_sorting.setObjectName("stop_sorting")
        self.horizontalLayout_10.addWidget(self.stop_sorting)
        self.horizontalLayout_12.addWidget(self.play_control)
        self.frame_shu = QtWidgets.QFrame(self.frame_controllers)
        self.frame_shu.setMaximumSize(QtCore.QSize(200, 25))
        self.frame_shu.setStyleSheet("")
        self.frame_shu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_shu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_shu.setObjectName("frame_shu")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_shu)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_shuffle = QtWidgets.QLabel(self.frame_shu)
        self.label_shuffle.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_shuffle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shuffle.setObjectName("label_shuffle")
        self.horizontalLayout_9.addWidget(self.label_shuffle)
        self.shuffle = QtWidgets.QComboBox(self.frame_shu)
        self.shuffle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.shuffle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.shuffle.setObjectName("shuffle")
        self.shuffle.addItem("")
        self.shuffle.addItem("")
        self.shuffle.addItem("")
        self.shuffle.addItem("")
        self.horizontalLayout_9.addWidget(self.shuffle)
        self.horizontalLayout_12.addWidget(self.frame_shu)
        self.verticalLayout_6.addWidget(self.frame_controllers)
        self.frame_visualizing = QtWidgets.QFrame(self.page_sorting)
        self.frame_visualizing.setStyleSheet("")
        self.frame_visualizing.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_visualizing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visualizing.setObjectName("frame_visualizing")
        self.verticalLayout_6.addWidget(self.frame_visualizing)
        self.stackedWidget.addWidget(self.page_sorting)
        self.page_tree = QtWidgets.QWidget()
        self.page_tree.setStyleSheet("    background-color: rgb(53, 81, 106);")
        self.page_tree.setObjectName("page_tree")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_tree)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_tree_controllers = QtWidgets.QFrame(self.page_tree)
        self.frame_tree_controllers.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_tree_controllers.setStyleSheet("background-color: rgb(31, 62, 90);\n"
"")
        self.frame_tree_controllers.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tree_controllers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tree_controllers.setObjectName("frame_tree_controllers")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_tree_controllers)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_input = QtWidgets.QFrame(self.frame_tree_controllers)
        self.frame_input.setMaximumSize(QtCore.QSize(80, 25))
        self.frame_input.setStyleSheet("")
        self.frame_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName("frame_input")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_input)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.inputArr = QtWidgets.QPushButton(self.frame_input)
        self.inputArr.setMaximumSize(QtCore.QSize(80, 25))
        self.inputArr.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(75, 100, 122) ; \n"
"    background-color: rgb(15, 57, 112); \n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.inputArr.setIconSize(QtCore.QSize(24, 24))
        self.inputArr.setObjectName("inputArr")
        self.verticalLayout_9.addWidget(self.inputArr)
        self.horizontalLayout_5.addWidget(self.frame_input)
        self.heapsort = QtWidgets.QPushButton(self.frame_tree_controllers)
        self.heapsort.setMaximumSize(QtCore.QSize(100, 25))
        self.heapsort.setStyleSheet("QPushButton {\n"
"    background-color: rgb(53, 81, 106);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.heapsort.setObjectName("heapsort")
        self.horizontalLayout_5.addWidget(self.heapsort)
        self.play_control_shuffleTrre = QtWidgets.QFrame(self.frame_tree_controllers)
        self.play_control_shuffleTrre.setMaximumSize(QtCore.QSize(350, 25))
        self.play_control_shuffleTrre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.play_control_shuffleTrre.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.play_control_shuffleTrre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.play_control_shuffleTrre.setObjectName("play_control_shuffleTrre")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.play_control_shuffleTrre)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.play_Tree = QtWidgets.QPushButton(self.play_control_shuffleTrre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_Tree.sizePolicy().hasHeightForWidth())
        self.play_Tree.setSizePolicy(sizePolicy)
        self.play_Tree.setMaximumSize(QtCore.QSize(50, 20))
        self.play_Tree.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"\n"
"\n"
"\n"
"    background-color: rgb(149, 175, 206);\n"
"    background-color: rgb(15, 57, 112); \n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.play_Tree.setText("")
        self.play_Tree.setIcon(icon3)
        self.play_Tree.setIconSize(QtCore.QSize(20, 20))
        self.play_Tree.setObjectName("play_Tree")
        self.horizontalLayout_16.addWidget(self.play_Tree)
        self.pause_Tree = QtWidgets.QPushButton(self.play_control_shuffleTrre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_Tree.sizePolicy().hasHeightForWidth())
        self.pause_Tree.setSizePolicy(sizePolicy)
        self.pause_Tree.setMaximumSize(QtCore.QSize(50, 20))
        self.pause_Tree.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(15, 57, 112); \n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pause_Tree.setText("")
        self.pause_Tree.setIcon(icon4)
        self.pause_Tree.setIconSize(QtCore.QSize(20, 20))
        self.pause_Tree.setObjectName("pause_Tree")
        self.horizontalLayout_16.addWidget(self.pause_Tree)
        self.stop_Tree = QtWidgets.QPushButton(self.play_control_shuffleTrre)
        self.stop_Tree.setMaximumSize(QtCore.QSize(50, 20))
        self.stop_Tree.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(75, 100, 122) ; \n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(15, 57, 112);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.stop_Tree.setText("")
        self.stop_Tree.setIcon(icon5)
        self.stop_Tree.setIconSize(QtCore.QSize(20, 20))
        self.stop_Tree.setObjectName("stop_Tree")
        self.horizontalLayout_16.addWidget(self.stop_Tree)
        self.horizontalLayout_5.addWidget(self.play_control_shuffleTrre)
        self.verticalLayout_7.addWidget(self.frame_tree_controllers)
        self.frame_visualizing_tree_2 = QtWidgets.QFrame(self.page_tree)
        self.frame_visualizing_tree_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(75, 100, 122);\n"
"background-color: rgb(53, 81, 106);")
        self.frame_visualizing_tree_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_visualizing_tree_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visualizing_tree_2.setObjectName("frame_visualizing_tree_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_visualizing_tree_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_visualizing_lefttree = QtWidgets.QFrame(self.frame_visualizing_tree_2)
        self.frame_visualizing_lefttree.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_visualizing_lefttree.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_visualizing_lefttree.setStyleSheet("background-color: rgb(21, 43, 62);\n"
"color: rgb(220, 220, 220);")
        self.frame_visualizing_lefttree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_visualizing_lefttree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visualizing_lefttree.setObjectName("frame_visualizing_lefttree")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_visualizing_lefttree)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBigO = QtWidgets.QGroupBox(self.frame_visualizing_lefttree)
        self.groupBigO.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBigO.setObjectName("groupBigO")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBigO)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.groupBigO)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.logN = QtWidgets.QRadioButton(self.frame_4)
        self.logN.setMaximumSize(QtCore.QSize(16777215, 25))
        self.logN.setObjectName("logN")
        self.horizontalLayout_17.addWidget(self.logN)
        self.oN = QtWidgets.QRadioButton(self.frame_4)
        self.oN.setMaximumSize(QtCore.QSize(60, 25))
        self.oN.setObjectName("oN")
        self.horizontalLayout_17.addWidget(self.oN)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.groupBigO)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkHeapSort = QtWidgets.QCheckBox(self.frame_3)
        self.checkHeapSort.setObjectName("checkHeapSort")
        self.horizontalLayout_18.addWidget(self.checkHeapSort)
        self.insertArray = QtWidgets.QPushButton(self.frame_3)
        self.insertArray.setObjectName("insertArray")
        self.horizontalLayout_18.addWidget(self.insertArray)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.verticalLayout_13.addWidget(self.groupBigO)
        self.frame_ele = QtWidgets.QFrame(self.frame_visualizing_lefttree)
        self.frame_ele.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_ele.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_ele.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ele.setObjectName("frame_ele")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_ele)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_insert_ele = QtWidgets.QFrame(self.frame_ele)
        self.frame_insert_ele.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_insert_ele.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_insert_ele.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_insert_ele.setObjectName("frame_insert_ele")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_insert_ele)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.insert_ele_button = QtWidgets.QPushButton(self.frame_insert_ele)
        self.insert_ele_button.setMaximumSize(QtCore.QSize(150, 25))
        self.insert_ele_button.setObjectName("insert_ele_button")
        self.horizontalLayout_14.addWidget(self.insert_ele_button)
        self.insert_ele = QtWidgets.QLineEdit(self.frame_insert_ele)
        self.insert_ele.setMaximumSize(QtCore.QSize(50, 25))
        self.insert_ele.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.insert_ele.setAlignment(QtCore.Qt.AlignCenter)
        self.insert_ele.setObjectName("insert_ele")
        self.horizontalLayout_14.addWidget(self.insert_ele)
        self.verticalLayout_11.addWidget(self.frame_insert_ele, 0, QtCore.Qt.AlignLeft)
        self.frame_extract_ele = QtWidgets.QFrame(self.frame_ele)
        self.frame_extract_ele.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_extract_ele.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extract_ele.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extract_ele.setObjectName("frame_extract_ele")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_extract_ele)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.extract_ele_button = QtWidgets.QPushButton(self.frame_extract_ele)
        self.extract_ele_button.setMaximumSize(QtCore.QSize(150, 25))
        self.extract_ele_button.setObjectName("extract_ele_button")
        self.horizontalLayout_13.addWidget(self.extract_ele_button)
        self.extract_ele = QtWidgets.QLabel(self.frame_extract_ele)
        self.extract_ele.setMaximumSize(QtCore.QSize(50, 25))
        self.extract_ele.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.extract_ele.setText("")
        self.extract_ele.setAlignment(QtCore.Qt.AlignCenter)
        self.extract_ele.setObjectName("extract_ele")
        self.horizontalLayout_13.addWidget(self.extract_ele)
        self.verticalLayout_11.addWidget(self.frame_extract_ele, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_13.addWidget(self.frame_ele)
        self.horizontalLayout_15.addWidget(self.frame_visualizing_lefttree, 0, QtCore.Qt.AlignTop)
        self.frame_visualizing_tree = QtWidgets.QFrame(self.frame_visualizing_tree_2)
        self.frame_visualizing_tree.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_visualizing_tree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_visualizing_tree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visualizing_tree.setObjectName("frame_visualizing_tree")
        self.horizontalLayout_15.addWidget(self.frame_visualizing_tree)
        self.verticalLayout_7.addWidget(self.frame_visualizing_tree_2)
        self.stackedWidget.addWidget(self.page_tree)
        self.page_linkedlist = QtWidgets.QWidget()
        self.page_linkedlist.setStyleSheet("    background-color: rgb(27, 55, 81);")
        self.page_linkedlist.setObjectName("page_linkedlist")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_linkedlist)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_linkedlist)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_8.addWidget(self.graphicsView)
        self.stackedWidget.addWidget(self.page_linkedlist)
        self.page_about = QtWidgets.QWidget()
        self.page_about.setObjectName("page_about")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_about)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page_about)
        self.label_4.setStyleSheet("font: 81pt \"Cantarell\";\n"
"color: rgb(252, 233, 79);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_about)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_pages)
        self.verticalLayout_2.addWidget(self.frame_center)
        self.frame_bottom = QtWidgets.QFrame(self.frame_main)
        self.frame_bottom.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.about_btn = QtWidgets.QPushButton(self.frame_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_btn.sizePolicy().hasHeightForWidth())
        self.about_btn.setSizePolicy(sizePolicy)
        self.about_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.about_btn.setMaximumSize(QtCore.QSize(25, 40))
        self.about_btn.setStyleSheet("QPushButton {\n"
"    background-position: center;\n"
"    background-image: url(:/24x24/icons/24x24/cil-options.png);\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(183, 207, 240);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    \n"
"    background-color: rgb(183, 207, 200);\n"
"}\n"
"\n"
"")
        self.about_btn.setText("")
        self.about_btn.setObjectName("about_btn")
        self.horizontalLayout_6.addWidget(self.about_btn)
        self.label_credits = QtWidgets.QLabel(self.frame_bottom)
        self.label_credits.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("background-color: rgb(24, 49, 72);\n"
"color: rgb(255, 255, 255);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_6.addWidget(self.label_credits)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_bottom)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(25, 25))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(25, 25))
        self.frame_size_grip.setStyleSheet("\n"
"    background-image: url(:/16x16/icons/16x16/cil-size-grip.png);\n"
"    background-position:  center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_6.addWidget(self.frame_size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frame_bottom)
        self.verticalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_des.setText(_translate("MainWindow", "TextLabel"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.sorting_btn.setText(_translate("MainWindow", "S"))
        self.tree_btn.setText(_translate("MainWindow", "T"))
        self.linkedlist_btn.setText(_translate("MainWindow", "L"))
        self.label_app_name.setText(_translate("MainWindow", "<Strong>Visualizer</strong><Strong>Tool</strong>"))
        self.label_app_description.setText(_translate("MainWindow", "<Strong>Visualize</strong> Your Success then Take Action"))
        self.label_algorithms.setText(_translate("MainWindow", "Algorithms"))
        self.algorithms.setItemText(0, _translate("MainWindow", "bubblesort"))
        self.algorithms.setItemText(1, _translate("MainWindow", "selectionsort"))
        self.algorithms.setItemText(2, _translate("MainWindow", "insertionsort"))
        self.algorithms.setItemText(3, _translate("MainWindow", "shellsort"))
        self.algorithms.setItemText(4, _translate("MainWindow", "mergesort"))
        self.algorithms.setItemText(5, _translate("MainWindow", "quicksort"))
        self.algorithms.setItemText(6, _translate("MainWindow", "hybrid_quick_sort"))
        self.label_shuffle.setText(_translate("MainWindow", "Shuffle"))
        self.shuffle.setItemText(0, _translate("MainWindow", "random"))
        self.shuffle.setItemText(1, _translate("MainWindow", "reversed"))
        self.shuffle.setItemText(2, _translate("MainWindow", "few_unique"))
        self.shuffle.setItemText(3, _translate("MainWindow", "nearly_sorted"))
        self.inputArr.setText(_translate("MainWindow", "Generate"))
        self.heapsort.setText(_translate("MainWindow", "HeapSort"))
        self.groupBigO.setTitle(_translate("MainWindow", "Build Heap"))
        self.logN.setText(_translate("MainWindow", "O(N Log N)"))
        self.oN.setText(_translate("MainWindow", "O(N)"))
        self.checkHeapSort.setText(_translate("MainWindow", "HeapSort"))
        self.insertArray.setText(_translate("MainWindow", "Insert-Array"))
        self.insert_ele_button.setText(_translate("MainWindow", "Insert"))
        self.extract_ele_button.setText(_translate("MainWindow", "Extract"))
        self.label_4.setText(_translate("MainWindow", "I Love You"))
        self.label_credits.setText(_translate("MainWindow", "Designed By: Hesham Bahgat"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
