# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SplashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(700, 495)
        SplashScreen.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/icons/earth.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 300, 678, 27))
        self.progressBar.setStyleSheet("\n"
"\n"
"QProgressBar {\n"
"    \n"
"    background-color: rgb(217, 228, 236);\n"
"    color: rgb(0, 0, 0);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgb(190, 213, 235), stop:1 rgb(89, 133, 175) );\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_app_name = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_app_name.setGeometry(QtCore.QRect(40, 20, 611, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_app_name.setFont(font)
        self.label_app_name.setAutoFillBackground(False)
        self.label_app_name.setStyleSheet("color: rgb(200, 200, 120);")
        self.label_app_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_app_name.setObjectName("label_app_name")
        self.label_credit = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credit.setGeometry(QtCore.QRect(490, 450, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_credit.setFont(font)
        self.label_credit.setStyleSheet("color: rgb(217, 228, 236) ;")
        self.label_credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credit.setObjectName("label_credit")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(290, 340, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_app_name.setText(_translate("SplashScreen", "<Strong>Visualizer</strong><Strong>Tool</strong>"))
        self.label_credit.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600;\">Created By</span>: Hesham Bahgat</p></body></html>"))
        self.label_loading.setText(_translate("SplashScreen", "<Strong>loading</Strong>"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
